# Site settings
title: Eternal Mountain
email: wbqdinno@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Eternal Mountain
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://wbqd.github.io" # the base hostname & protocol for your site
twitter_username: wbqd
github_username:  wbqd

# Build settings
markdown: kramdown
